version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: serverless-dotenv-plugin
    versions:
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.5.1
    - 3.8.0
    - 3.8.1
    - 3.8.2
  - dependency-name: react-cookie-consent
    versions:
    - 6.2.2
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: serverless-offline
    versions:
    - 6.8.0
