service: ${file(./config.${opt:stage, 'dev'}.json):SERVICE}
configValidationMode: error
useDotenv: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true

functions:
  server:
    handler: index.server
    environment:
      STAGE: ${opt:stage, 'dev'}
      NODE_ENV: production
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  apigwBinary:
    types:
      - "*/*"

plugins:
  - serverless-apigw-binary

package:
  patterns:
    - "!pages/**"
    - "!components/**"
    - "!src/**"
    - "!utils/**"
    - "!out/**"
    - "!.next/cache/**"
