service: ${file(./config.${self:custom.currentStage}.json):SERVICE}
useDotenv: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs10.x
  stage: ${env:NODE_ENV}
  region: eu-west-1
  environment:
    NODE_ENV: ${env:NODE_ENV}
  apiGateway:
    shouldStartNameWithService: true

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  apigwBinary:
    types:
      - "*/*"

package:
  exclude:
    - pages/**
    - components/**
    - src/**
    - utils/**
    - out/**
    - .next/cache/**
